name: autoformer
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - pip
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - SummaryWriter
  - pip:
    - torch==1.9.0
